package com.foodorder.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.foodorder.db.bean.Order;
import com.foodorder.db.bean.Good;
import com.foodorder.db.bean.Attribute;
import com.foodorder.db.bean.GoodType;
import com.foodorder.db.bean.Formula;

import com.foodorder.db.OrderDao;
import com.foodorder.db.GoodDao;
import com.foodorder.db.AttributeDao;
import com.foodorder.db.GoodTypeDao;
import com.foodorder.db.FormulaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig goodDaoConfig;
    private final DaoConfig attributeDaoConfig;
    private final DaoConfig goodTypeDaoConfig;
    private final DaoConfig formulaDaoConfig;

    private final OrderDao orderDao;
    private final GoodDao goodDao;
    private final AttributeDao attributeDao;
    private final GoodTypeDao goodTypeDao;
    private final FormulaDao formulaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        goodDaoConfig = daoConfigMap.get(GoodDao.class).clone();
        goodDaoConfig.initIdentityScope(type);

        attributeDaoConfig = daoConfigMap.get(AttributeDao.class).clone();
        attributeDaoConfig.initIdentityScope(type);

        goodTypeDaoConfig = daoConfigMap.get(GoodTypeDao.class).clone();
        goodTypeDaoConfig.initIdentityScope(type);

        formulaDaoConfig = daoConfigMap.get(FormulaDao.class).clone();
        formulaDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        goodDao = new GoodDao(goodDaoConfig, this);
        attributeDao = new AttributeDao(attributeDaoConfig, this);
        goodTypeDao = new GoodTypeDao(goodTypeDaoConfig, this);
        formulaDao = new FormulaDao(formulaDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(Good.class, goodDao);
        registerDao(Attribute.class, attributeDao);
        registerDao(GoodType.class, goodTypeDao);
        registerDao(Formula.class, formulaDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        goodDaoConfig.clearIdentityScope();
        attributeDaoConfig.clearIdentityScope();
        goodTypeDaoConfig.clearIdentityScope();
        formulaDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public GoodDao getGoodDao() {
        return goodDao;
    }

    public AttributeDao getAttributeDao() {
        return attributeDao;
    }

    public GoodTypeDao getGoodTypeDao() {
        return goodTypeDao;
    }

    public FormulaDao getFormulaDao() {
        return formulaDao;
    }

}
