package com.foodorder.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.foodorder.db.bean.Formula;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FORMULA".
*/
public class FormulaDao extends AbstractDao<Formula, Long> {

    public static final String TABLENAME = "FORMULA";

    /**
     * Properties of entity Formula.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_product = new Property(1, String.class, "id_product", false, "ID_PRODUCT");
        public final static Property Id_product_formula = new Property(2, String.class, "id_product_formula", false, "ID_PRODUCT_FORMULA");
        public final static Property Zh_type_name = new Property(3, String.class, "zh_type_name", false, "ZH_TYPE_NAME");
        public final static Property Fr_type_name = new Property(4, String.class, "fr_type_name", false, "FR_TYPE_NAME");
        public final static Property Max_choose = new Property(5, int.class, "max_choose", false, "MAX_CHOOSE");
        public final static Property Id_product_formula_item = new Property(6, String.class, "id_product_formula_item", false, "ID_PRODUCT_FORMULA_ITEM");
        public final static Property Id_product_item = new Property(7, String.class, "id_product_item", false, "ID_PRODUCT_ITEM");
        public final static Property Position = new Property(8, int.class, "position", false, "POSITION");
        public final static Property Zh_name = new Property(9, String.class, "zh_name", false, "ZH_NAME");
        public final static Property Fr_name = new Property(10, String.class, "fr_name", false, "FR_NAME");
        public final static Property Image_url = new Property(11, String.class, "image_url", false, "IMAGE_URL");
    }

    private Query<Formula> good_FormulaListQuery;

    public FormulaDao(DaoConfig config) {
        super(config);
    }
    
    public FormulaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FORMULA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ID_PRODUCT\" TEXT," + // 1: id_product
                "\"ID_PRODUCT_FORMULA\" TEXT," + // 2: id_product_formula
                "\"ZH_TYPE_NAME\" TEXT," + // 3: zh_type_name
                "\"FR_TYPE_NAME\" TEXT," + // 4: fr_type_name
                "\"MAX_CHOOSE\" INTEGER NOT NULL ," + // 5: max_choose
                "\"ID_PRODUCT_FORMULA_ITEM\" TEXT," + // 6: id_product_formula_item
                "\"ID_PRODUCT_ITEM\" TEXT," + // 7: id_product_item
                "\"POSITION\" INTEGER NOT NULL ," + // 8: position
                "\"ZH_NAME\" TEXT," + // 9: zh_name
                "\"FR_NAME\" TEXT," + // 10: fr_name
                "\"IMAGE_URL\" TEXT);"); // 11: image_url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FORMULA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Formula entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String id_product = entity.getId_product();
        if (id_product != null) {
            stmt.bindString(2, id_product);
        }
 
        String id_product_formula = entity.getId_product_formula();
        if (id_product_formula != null) {
            stmt.bindString(3, id_product_formula);
        }
 
        String zh_type_name = entity.getZh_type_name();
        if (zh_type_name != null) {
            stmt.bindString(4, zh_type_name);
        }
 
        String fr_type_name = entity.getFr_type_name();
        if (fr_type_name != null) {
            stmt.bindString(5, fr_type_name);
        }
        stmt.bindLong(6, entity.getMax_choose());
 
        String id_product_formula_item = entity.getId_product_formula_item();
        if (id_product_formula_item != null) {
            stmt.bindString(7, id_product_formula_item);
        }
 
        String id_product_item = entity.getId_product_item();
        if (id_product_item != null) {
            stmt.bindString(8, id_product_item);
        }
        stmt.bindLong(9, entity.getPosition());
 
        String zh_name = entity.getZh_name();
        if (zh_name != null) {
            stmt.bindString(10, zh_name);
        }
 
        String fr_name = entity.getFr_name();
        if (fr_name != null) {
            stmt.bindString(11, fr_name);
        }
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(12, image_url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Formula entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String id_product = entity.getId_product();
        if (id_product != null) {
            stmt.bindString(2, id_product);
        }
 
        String id_product_formula = entity.getId_product_formula();
        if (id_product_formula != null) {
            stmt.bindString(3, id_product_formula);
        }
 
        String zh_type_name = entity.getZh_type_name();
        if (zh_type_name != null) {
            stmt.bindString(4, zh_type_name);
        }
 
        String fr_type_name = entity.getFr_type_name();
        if (fr_type_name != null) {
            stmt.bindString(5, fr_type_name);
        }
        stmt.bindLong(6, entity.getMax_choose());
 
        String id_product_formula_item = entity.getId_product_formula_item();
        if (id_product_formula_item != null) {
            stmt.bindString(7, id_product_formula_item);
        }
 
        String id_product_item = entity.getId_product_item();
        if (id_product_item != null) {
            stmt.bindString(8, id_product_item);
        }
        stmt.bindLong(9, entity.getPosition());
 
        String zh_name = entity.getZh_name();
        if (zh_name != null) {
            stmt.bindString(10, zh_name);
        }
 
        String fr_name = entity.getFr_name();
        if (fr_name != null) {
            stmt.bindString(11, fr_name);
        }
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(12, image_url);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Formula readEntity(Cursor cursor, int offset) {
        Formula entity = new Formula( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id_product
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id_product_formula
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // zh_type_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fr_type_name
            cursor.getInt(offset + 5), // max_choose
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // id_product_formula_item
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // id_product_item
            cursor.getInt(offset + 8), // position
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // zh_name
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // fr_name
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // image_url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Formula entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_product(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId_product_formula(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setZh_type_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFr_type_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMax_choose(cursor.getInt(offset + 5));
        entity.setId_product_formula_item(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setId_product_item(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPosition(cursor.getInt(offset + 8));
        entity.setZh_name(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFr_name(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setImage_url(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Formula entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Formula entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Formula entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "formulaList" to-many relationship of Good. */
    public List<Formula> _queryGood_FormulaList(String id_product) {
        synchronized (this) {
            if (good_FormulaListQuery == null) {
                QueryBuilder<Formula> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id_product.eq(null));
                good_FormulaListQuery = queryBuilder.build();
            }
        }
        Query<Formula> query = good_FormulaListQuery.forCurrentThread();
        query.setParameter(0, id_product);
        return query.list();
    }

}
