package com.foodorder.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.foodorder.db.bean.Good;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOOD".
*/
public class GoodDao extends AbstractDao<Good, Long> {

    public static final String TABLENAME = "GOOD";

    /**
     * Properties of entity Good.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Id_product = new Property(1, String.class, "id_product", false, "ID_PRODUCT");
        public final static Property Reference = new Property(2, String.class, "reference", false, "REFERENCE");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Quantity = new Property(4, int.class, "quantity", false, "QUANTITY");
        public final static Property Unit = new Property(5, String.class, "unit", false, "UNIT");
        public final static Property Price = new Property(6, double.class, "price", false, "PRICE");
        public final static Property Reducable = new Property(7, boolean.class, "reducable", false, "REDUCABLE");
        public final static Property Max_attributes_choose = new Property(8, int.class, "max_attributes_choose", false, "MAX_ATTRIBUTES_CHOOSE");
        public final static Property Image_url = new Property(9, String.class, "image_url", false, "IMAGE_URL");
    }

    private DaoSession daoSession;


    public GoodDao(DaoConfig config) {
        super(config);
    }
    
    public GoodDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOOD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"ID_PRODUCT\" TEXT," + // 1: id_product
                "\"REFERENCE\" TEXT," + // 2: reference
                "\"NAME\" TEXT," + // 3: name
                "\"QUANTITY\" INTEGER NOT NULL ," + // 4: quantity
                "\"UNIT\" TEXT," + // 5: unit
                "\"PRICE\" REAL NOT NULL ," + // 6: price
                "\"REDUCABLE\" INTEGER NOT NULL ," + // 7: reducable
                "\"MAX_ATTRIBUTES_CHOOSE\" INTEGER NOT NULL ," + // 8: max_attributes_choose
                "\"IMAGE_URL\" TEXT);"); // 9: image_url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOOD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Good entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String id_product = entity.getId_product();
        if (id_product != null) {
            stmt.bindString(2, id_product);
        }
 
        String reference = entity.getReference();
        if (reference != null) {
            stmt.bindString(3, reference);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getQuantity());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(6, unit);
        }
        stmt.bindDouble(7, entity.getPrice());
        stmt.bindLong(8, entity.getReducable() ? 1L: 0L);
        stmt.bindLong(9, entity.getMax_attributes_choose());
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(10, image_url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Good entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String id_product = entity.getId_product();
        if (id_product != null) {
            stmt.bindString(2, id_product);
        }
 
        String reference = entity.getReference();
        if (reference != null) {
            stmt.bindString(3, reference);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getQuantity());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(6, unit);
        }
        stmt.bindDouble(7, entity.getPrice());
        stmt.bindLong(8, entity.getReducable() ? 1L: 0L);
        stmt.bindLong(9, entity.getMax_attributes_choose());
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(10, image_url);
        }
    }

    @Override
    protected final void attachEntity(Good entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Good readEntity(Cursor cursor, int offset) {
        Good entity = new Good( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id_product
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // reference
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // quantity
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // unit
            cursor.getDouble(offset + 6), // price
            cursor.getShort(offset + 7) != 0, // reducable
            cursor.getInt(offset + 8), // max_attributes_choose
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // image_url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Good entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setId_product(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReference(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQuantity(cursor.getInt(offset + 4));
        entity.setUnit(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPrice(cursor.getDouble(offset + 6));
        entity.setReducable(cursor.getShort(offset + 7) != 0);
        entity.setMax_attributes_choose(cursor.getInt(offset + 8));
        entity.setImage_url(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Good entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Good entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Good entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
